[bastion]
93.77.180.0

[zabbix]
10.0.3.13

[zabbix:vars]
ansible_user = user
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@93.77.180.0"'

[elasticsearch]
10.0.2.32
  
[elasticsearch:vars]
ansible_user = user
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@93.77.180.0"'

[kibana]
10.0.3.7

[kibana:vars]
ansible_user = user
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@93.77.180.0"'

[webservers]
10.0.1.4
10.0.2.27

[webservers:vars]
ansible_user = user
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@93.77.180.0"'
